export const SagaType = {
    GET_HOME_BANNER:'GET_HOME_BANNER',
    GET_FILM_REVIEWS_API:'GET_FILM_REVIEWS_API',

    LOGIN_API:'LOGIN_API',

    GET_FILM_DETAIL_API: 'GET_FILM_DETAIL_API',

    GET_SEAT_LIST_API: 'GET_SEAT_LIST_API',
}