export const HomeType = {
    TAKE_BANNERS:'TAKE_BANNERS',
    GET_FILM_REVIEW:'GET_FILM_REVIEW',

    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',

    OPEN_LOADING: 'OPEN_LOADING',
    CLOSE_LOADING: 'CLOSE_LOADING',
}